### ISSUE TITLE
TypeError·Uncaught TypeError: Property '[object Object]' of object [object Array] is not a function

### ISSUE THREAD

**Issue by itxuye** [vifird/react-keeper#30]
TypeError·Uncaught TypeError: Property '[object Object]' of object [object Array] is not a function
at iterator (webpack:///~/react-keeper/CacheOfTagControl.js:24:0)
at put (webpack:///~/react-keeper/RouteUtil.js:87:0)
at checkCacheTag (webpack:///~/react-keeper/Route.js:172:0)
at updateMountStatus (webpack:///~/react-keeper/Route.js:117:0)
at callback (webpack:///~/react-keeper/RouteUtil.js:166:0)
at checkFilter (webpack:///~/react-keeper/Route.js:104:0)
at callback (webpack:///~/react-keeper/RouteUtil.js:154:0)
at loadComponent (webpack:///~/react-keeper/Route.js:97:0)
at setToMount (webpack:///~/react-keeper/Route.js:85:0)
at routeCheckEntry (webpack:///~/react-keeper/Route.js:66:0)
在真机上 华为Mate7/8，传回的错误日志。

**Comment by itxuye** [comment]
发现部分Android手机出现问题，是因为Symbol吗。我试着polyfill没有解决。

**Comment by vifird** [comment]
@itxuye 不太确定，我们测试一下。

**Comment by itxuye** [comment]
@vifird 目前在5.0以下的手机发现这个问题，所以问下你们在低版本Android手机中有问题吗？方便我测试下，谢谢

**Comment by itxuye** [comment]
用了core-js解决了。
